# -*- coding: utf-8 -*-
"""A-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18lDgEDDObD8V3yA7v_D4qPwSbf1f7xpG

***Title: Descriptive Statistics - Measures of Central Tendency and variability***
Perform the following operations on any open source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a 
dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical) 
variable. For example, if your categorical variable is age groups and quantitative variable is 
income, then provide summary statistics of income grouped by the age groups. Create a list that 
contains a numeric value for each response to the categorical variable.
2. Write a Python program to display some basic statistical details like percentile, mean, standard 
deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ of iris.csv 
dataset.
Provide the codes with outputs and explain everything that you do in this step.
"""

# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics as st

# reading the csv file
data = pd.read_csv('Iris.csv')

# to print the first 10 values
print(data.head())

# desribing the data
data.describe()

np.unique(data['Species'])

# Finding the mean for species on SepalWidth using groupby from pandas
sepal_width = data.groupby("Species")["SepalWidthCm"].mean()
print(sepal_width)

# Finding the mean for species on SepalLength using groupby from pandas
sepal_length = data.groupby("Species")["SepalLengthCm"].mean()
print(sepal_length)

# Finding the median for species on PetalWidth using groupby from pandas
petal_width_median = data.groupby("Species")["PetalWidthCm"].median()
print(petal_width_median)

# Finding the minimum for species on PetalLength using groupby from pandas
petal_length_min = data.groupby("Species")["PetalLengthCm"].min()
print(petal_length_min)

# Finding the maximum for species on PetalWidth using groupby from pandas
petal_width_max = data.groupby("Species")["PetalLengthCm"].max()
print(petal_width_max)

# Finding the standard deviation for species on PetalLength using groupby from pandas
petal_length_std = data.groupby("Species")["PetalLengthCm"].std()
print(petal_length_std)

# Using statistics library for fidning standard deviations
sd2 = st.stdev(data["SepalWidthCm"])
print(sd2)

# Finding the occurence
# value_counts() returns a Series containing counts of unique values
occurence = data["Species"].value_counts()
print("Occurence is:", occurence)

# Percentiles
Q1 = data['SepalWidthCm'].quantile(0.25)
Q3 = data['SepalWidthCm'].quantile(0.75)
print("25 percentile:", Q1)
print("75 percentile", Q3)