# -*- coding: utf-8 -*-
"""A-9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103wqnj9SPJvYoFB7m6FwSoNcCdNn1WgN

***Title: Data Visualization-II***
1. Use the inbuilt dataset 'titanic' as used in the above problem. Plot a box plot for distribution of 
age with respect to each gender along with the information about whether they survived or not. 
(Column names : 'sex' and 'age')
2. Write observations on the inference from the above statistics.
"""

# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings
filterwarnings('ignore')

titanic = pd.read_csv('titanic.csv')
titanic.head()

titanic.info()

titanic.describe()

plt.figure(figsize=(12,7))
# boxplot - shows the distribution of quantitative data in a way that facilitates comparisons between variables
sns.boxplot(data = titanic, x='Sex', y='Age', palette = 'winter')

plt.figure(figsize=(12,7))
sns.boxplot(data=titanic, x='Pclass', y='Age')